development:
  adapter: async

test:
  adapter: async

production:
  # heroku用
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: skip2_production
  adapter: async